services:
  mariadb:
    container_name: ${PROJECT_TAG}-mariadb
    image: mariadb:lts
    user: "mysql"
    env_file:
      - ".env"
    volumes:
      - "mariadb_data:/var/lib/mysql"
      - "./mariadb/init.sh:/docker-entrypoint-initdb.d/init.sh"
    restart: unless-stopped
    expose:
      - "3306"
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      interval: 120s
      timeout: 5s
      retries: 2
      start_period: 30s
  wordpress:
    container_name: ${PROJECT_TAG}-wordpress
    image: wordpress:6-php8.3-apache
    user: "www-data"
    depends_on:
      mariadb:
        condition: service_started
    env_file:
      - ".env"
    volumes:
      - "wordpress_data:/var/www/html"
    ports:
      - "${WORDPRESS_PORT}:80/tcp"
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 120s
      timeout: 5s
      retries: 2
      start_period: 30s
  wordpress-cli:
    container_name: ${PROJECT_TAG}-wordpress-cli
    image: wordpress:cli-php8.3
    user: "www-data"
    depends_on:
      mariadb:
        condition: service_started
    profiles:
      - wordpress-cli
    entrypoint: wp
    command: ["cli", "version"]
    env_file:
      - ".env"
    volumes:
      - "wordpress_data:/var/www/html"
    restart: no
  sftp:
    container_name: ${PROJECT_TAG}-sftp
    image: atmoz/sftp:alpine
    depends_on:
      wordpress:
        condition: service_started
    profiles:
      - sftp
    env_file:
      - ".env"
    volumes:
      - "wordpress_data:/home/${SFTP_USER}/wordpress"
    ports:
      - "${SFTP_PORT}:22/tcp"
    restart: unless-stopped
    command: ${SFTP_USER}:${SFTP_PASSWORD}:${SFTP_UID}:${SFTP_GID}
    healthcheck:
      test: sshd -t && netstat -ntulp | grep -q "0.0.0.0:22"
      interval: 120s
      timeout: 5s
      retries: 2
      start_period: 30s
  mysqld-exporter:
    container_name: ${PROJECT_TAG}-mysqld-exporter
    image: prom/mysqld-exporter:latest
    user: "nobody"
    command: "--mysqld.username=exporter --mysqld.address=mariadb:3306 --config.my-cnf=/my.cnf"
    depends_on:
      mariadb:
        condition: service_started
    env_file:
      - ".env"
    volumes:
      - "./mariadb/my.cnf:/my.cnf:ro"
    ports:
      - "${MYSQLD_EXPORTER_PORT}:9104/tcp"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    healthcheck:
      test: wget -q -O - 127.0.0.1:9104/metrics | grep -q "mysql_up 1"
      interval: 120s
      timeout: 5s
      retries: 2
      start_period: 30s

volumes:
  mariadb_data:
  wordpress_data:
