name: Approve and Merge Dependabot's PR
on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write
  contents: write
  actions: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: "audit"

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ github.token }}

      - name: Dependency Review
        uses: actions/dependency-review-action@0c155c5e8556a497adf53f2c18edabf945ed8e70 # v4.3.2
        with:
          license-check: true
          vulnerability-check: true
          fail-on-severity: "low"

      - name: Fetch Dependabot metadata
        uses: dependabot/fetch-metadata@5e5f99653a5b510e8555840e80cbf1514ad4af38 # v2.1.0
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: ${{ github.token }}

      - name: Approve and Merge PR
        uses: fastify/github-action-merge-dependabot@9e7bfb249c69139d7bdcd8d984f9665edd49020b # v3.10.1
        with:
          approve-only: false
          merge-comment: "I'm **approving** this PR because **it includes dependency update**"
          use-github-auto-merge: false
